version: 2
updates:
  - package-ecosystem: npm
    directory: "/src/BHS.Web/ClientApp"
    schedule:
      interval: weekly
      day: saturday
    ignore:
      - dependency-name: "@angular*"
      - dependency-name: "rxjs"
      - dependency-name: "zone.js"
      - dependency-name: "typescript"
      - dependency-name: "tslib"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
