version: 2
updates:
  - package-ecosystem: npm
    directory: "/src/BHS.Web/ClientApp"
    schedule:
      interval: weekly
      day: saturday
    ignore:
      - dependency-name: "@angular*"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: terraform
    directory: "/infrastructure/modules/env-specific"
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: terraform
    directory: "/infrastructure/modules/shared"
    schedule:
      interval: weekly
      day: saturday
