version: 2
updates:
  - package-ecosystem: npm
    directory: "/src/bhs-web-angular-app"
    schedule:
      interval: weekly
      day: saturday
    ignore:
      - dependency-name: "@angular*"
      - dependency-name: "rxjs"
      - dependency-name: "zone.js"
      - dependency-name: "typescript"
      - dependency-name: "tslib"
    groups:
      lodash:
        patterns:
          - "lodash"
          - "@types/lodash"
      lint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
      jest:
        patterns:
          - "jest*"
          - "@types/jest"
      cypress:
        patterns:
          - "cypress*"
          - "@cypress/schematic"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
        update-types:
          - "minor"
          - "patch"
      xunit:
        patterns:
          - "xunit*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
