dedupePluginMode: dependabot-only

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - checksum: e5e6e2885ab0e6521b70b0af7c6d8ca2c75dcae2403706fc4600a783b339a6530a476dafb9450c9436ca4050eb6bdee9b62e6e2cebfecf1e81dd709a2480dc07
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - checksum: c43fb18b0cc042871a14ddc76ec78d35b4bc6896ec1d2b75d137cfc6b6b3e2a83fe6cb8b1d2657700b460e81d843b8dc33c5330db1cce2cffe2d91ce0442eb14
    path: .yarn/plugins/@yarnpkg/plugin-dedupe.cjs
    spec: "https://github.com/blimmer/yarn-plugin-dedupe/releases/download/v1.0.0/plugin-dedupe.js"
