<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">bhs-web-angular-app</PackageJsonName>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">0.0.0</PackageJsonVersion>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonDescription Condition="$(PackageJsonDescription) == ''">Client-side Angular application for BHS.NET</PackageJsonDescription>
    <PackageJsonType Condition="$(PackageJsonType) == ''">commonjs</PackageJsonType>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">node ../bhs-generated-models/check-codegen.mjs &amp;&amp; ng build</PackageJsonScriptsBuild>
    <PackageJsonScriptsBuildRelease Condition="$(PackageJsonScriptsBuildRelease) == ''">ng build --configuration release</PackageJsonScriptsBuildRelease>
    <PackageJsonScriptsClean Condition="$(PackageJsonScriptsClean) == ''">ng cache clean</PackageJsonScriptsClean>
    <PackageJsonScriptsLint Condition="$(PackageJsonScriptsLint) == ''">ng lint</PackageJsonScriptsLint>
    <PackageJsonScriptsStart Condition="$(PackageJsonScriptsStart) == ''">ng serve</PackageJsonScriptsStart>
    <PackageJsonScriptsStartProxy Condition="$(PackageJsonScriptsStartProxy) == ''">node scripts/aspnetcore-https.mjs &amp;&amp; run-script-os</PackageJsonScriptsStartProxy>
    <PackageJsonScriptsStartProxyDefault Condition="$(PackageJsonScriptsStartProxyDefault) == ''">ng serve --configuration proxy --ssl-cert "$HOME/.aspnet/https/$npm_package_name.pem" --ssl-key "$HOME/.aspnet/https/$npm_package_name.key"</PackageJsonScriptsStartProxyDefault>
    <PackageJsonScriptsStartProxyWindows Condition="$(PackageJsonScriptsStartProxyWindows) == ''">ng serve --configuration proxy --ssl-cert "%APPDATA%\ASP.NET\https\%npm_package_name%.pem" --ssl-key "%APPDATA%\ASP.NET\https\%npm_package_name%.key"</PackageJsonScriptsStartProxyWindows>
    <PackageJsonScriptsTest Condition="$(PackageJsonScriptsTest) == ''">ng test</PackageJsonScriptsTest>
    <PackageJsonScriptsTestCi Condition="$(PackageJsonScriptsTestCi) == ''">ng test --configuration ci</PackageJsonScriptsTestCi>
    <PackageJsonScriptsTransformRelease Condition="$(PackageJsonScriptsTransformRelease) == ''">node scripts/transform-release.mjs</PackageJsonScriptsTransformRelease>
    <PackageJsonDependenciesAngularCommon Condition="$(PackageJsonDependenciesAngularCommon) == ''">22.1.5</PackageJsonDependenciesAngularCommon>
    <PackageJsonDependenciesAngularCompiler Condition="$(PackageJsonDependenciesAngularCompiler) == ''">22.1.5</PackageJsonDependenciesAngularCompiler>
    <PackageJsonDependenciesAngularCore Condition="$(PackageJsonDependenciesAngularCore) == ''">22.1.5</PackageJsonDependenciesAngularCore>
    <PackageJsonDependenciesAngularForms Condition="$(PackageJsonDependenciesAngularForms) == ''">22.1.5</PackageJsonDependenciesAngularForms>
    <PackageJsonDependenciesAngularPlatformBrowser Condition="$(PackageJsonDependenciesAngularPlatformBrowser) == ''">22.1.5</PackageJsonDependenciesAngularPlatformBrowser>
    <PackageJsonDependenciesAngularRouter Condition="$(PackageJsonDependenciesAngularRouter) == ''">22.1.5</PackageJsonDependenciesAngularRouter>
    <PackageJsonDependenciesAuth0Auth0Angular Condition="$(PackageJsonDependenciesAuth0Auth0Angular) == ''">^2.11.0</PackageJsonDependenciesAuth0Auth0Angular>
    <PackageJsonDependenciesMicrosoftApplicationinsightsAnalyticsJs Condition="$(PackageJsonDependenciesMicrosoftApplicationinsightsAnalyticsJs) == ''">3.4.3</PackageJsonDependenciesMicrosoftApplicationinsightsAnalyticsJs>
    <PackageJsonDependenciesMicrosoftApplicationinsightsAngularpluginJs Condition="$(PackageJsonDependenciesMicrosoftApplicationinsightsAngularpluginJs) == ''">^15.4.1</PackageJsonDependenciesMicrosoftApplicationinsightsAngularpluginJs>
    <PackageJsonDependenciesMicrosoftApplicationinsightsWeb Condition="$(PackageJsonDependenciesMicrosoftApplicationinsightsWeb) == ''">^3.4.3</PackageJsonDependenciesMicrosoftApplicationinsightsWeb>
    <PackageJsonDependenciesOpenngNgxToastr Condition="$(PackageJsonDependenciesOpenngNgxToastr) == ''">^1.1.0</PackageJsonDependenciesOpenngNgxToastr>
    <PackageJsonDependenciesStandardSchemaSpec Condition="$(PackageJsonDependenciesStandardSchemaSpec) == ''">^1.1.0</PackageJsonDependenciesStandardSchemaSpec>
    <PackageJsonDependenciesBhsGeneratedModels Condition="$(PackageJsonDependenciesBhsGeneratedModels) == ''">workspace:^</PackageJsonDependenciesBhsGeneratedModels>
    <PackageJsonDependenciesBootstrapIcons Condition="$(PackageJsonDependenciesBootstrapIcons) == ''">1.13.1</PackageJsonDependenciesBootstrapIcons>
    <PackageJsonDependenciesJwtDecode Condition="$(PackageJsonDependenciesJwtDecode) == ''">^4.0.0</PackageJsonDependenciesJwtDecode>
    <PackageJsonDependenciesMarked Condition="$(PackageJsonDependenciesMarked) == ''">^17.0.4</PackageJsonDependenciesMarked>
    <PackageJsonDependenciesPrettyMs Condition="$(PackageJsonDependenciesPrettyMs) == ''">^9.3.0</PackageJsonDependenciesPrettyMs>
    <PackageJsonDependenciesRxjs Condition="$(PackageJsonDependenciesRxjs) == ''">^7.8.2</PackageJsonDependenciesRxjs>
    <PackageJsonDependenciesTslib Condition="$(PackageJsonDependenciesTslib) == ''">^2.8.1</PackageJsonDependenciesTslib>
    <PackageJsonDependenciesZod Condition="$(PackageJsonDependenciesZod) == ''">^4.3.5</PackageJsonDependenciesZod>
    <PackageJsonDevdependenciesAngularBuild Condition="$(PackageJsonDevdependenciesAngularBuild) == ''">^22.1.7</PackageJsonDevdependenciesAngularBuild>
    <PackageJsonDevdependenciesAngularCli Condition="$(PackageJsonDevdependenciesAngularCli) == ''">22.1.7</PackageJsonDevdependenciesAngularCli>
    <PackageJsonDevdependenciesAngularCompilerCli Condition="$(PackageJsonDevdependenciesAngularCompilerCli) == ''">22.1.5</PackageJsonDevdependenciesAngularCompilerCli>
    <PackageJsonDevdependenciesEslintJs Condition="$(PackageJsonDevdependenciesEslintJs) == ''">^10.0.1</PackageJsonDevdependenciesEslintJs>
    <PackageJsonDevdependenciesStylisticEslintPlugin Condition="$(PackageJsonDevdependenciesStylisticEslintPlugin) == ''">^5.10.0</PackageJsonDevdependenciesStylisticEslintPlugin>
    <PackageJsonDevdependenciesTailwindcssPostcss Condition="$(PackageJsonDevdependenciesTailwindcssPostcss) == ''">^4.3.3</PackageJsonDevdependenciesTailwindcssPostcss>
    <PackageJsonDevdependenciesTailwindcssTypography Condition="$(PackageJsonDevdependenciesTailwindcssTypography) == ''">^0.5.20</PackageJsonDevdependenciesTailwindcssTypography>
    <PackageJsonDevdependenciesVitestCoverageV8 Condition="$(PackageJsonDevdependenciesVitestCoverageV8) == ''">^4.1.11</PackageJsonDevdependenciesVitestCoverageV8>
    <PackageJsonDevdependenciesVitestEslintPlugin Condition="$(PackageJsonDevdependenciesVitestEslintPlugin) == ''">^1.6.27</PackageJsonDevdependenciesVitestEslintPlugin>
    <PackageJsonDevdependenciesAngularEslint Condition="$(PackageJsonDevdependenciesAngularEslint) == ''">22.2.0</PackageJsonDevdependenciesAngularEslint>
    <PackageJsonDevdependenciesDaisyui Condition="$(PackageJsonDevdependenciesDaisyui) == ''">^5.6.18</PackageJsonDevdependenciesDaisyui>
    <PackageJsonDevdependenciesEslint Condition="$(PackageJsonDevdependenciesEslint) == ''">^10.9.1</PackageJsonDevdependenciesEslint>
    <PackageJsonDevdependenciesEslintConfigFlatGitignore Condition="$(PackageJsonDevdependenciesEslintConfigFlatGitignore) == ''">^2.4.0</PackageJsonDevdependenciesEslintConfigFlatGitignore>
    <PackageJsonDevdependenciesEslintImportResolverTypescript Condition="$(PackageJsonDevdependenciesEslintImportResolverTypescript) == ''">^4.4.5</PackageJsonDevdependenciesEslintImportResolverTypescript>
    <PackageJsonDevdependenciesEslintPluginBetterTailwindcss Condition="$(PackageJsonDevdependenciesEslintPluginBetterTailwindcss) == ''">~4.3.2</PackageJsonDevdependenciesEslintPluginBetterTailwindcss>
    <PackageJsonDevdependenciesEslintPluginImportX Condition="$(PackageJsonDevdependenciesEslintPluginImportX) == ''">^4.17.1</PackageJsonDevdependenciesEslintPluginImportX>
    <PackageJsonDevdependenciesEslintPluginJsdoc Condition="$(PackageJsonDevdependenciesEslintPluginJsdoc) == ''">^64.3.2</PackageJsonDevdependenciesEslintPluginJsdoc>
    <PackageJsonDevdependenciesEslintPluginPackageJson Condition="$(PackageJsonDevdependenciesEslintPluginPackageJson) == ''">^1.8.0</PackageJsonDevdependenciesEslintPluginPackageJson>
    <PackageJsonDevdependenciesEslintPluginPerfectionist Condition="$(PackageJsonDevdependenciesEslintPluginPerfectionist) == ''">^5.10.1</PackageJsonDevdependenciesEslintPluginPerfectionist>
    <PackageJsonDevdependenciesEslintPluginRegexp Condition="$(PackageJsonDevdependenciesEslintPluginRegexp) == ''">^3.2.0</PackageJsonDevdependenciesEslintPluginRegexp>
    <PackageJsonDevdependenciesEslintPluginRxjsAngularX Condition="$(PackageJsonDevdependenciesEslintPluginRxjsAngularX) == ''">^1.0.1</PackageJsonDevdependenciesEslintPluginRxjsAngularX>
    <PackageJsonDevdependenciesEslintPluginRxjsX Condition="$(PackageJsonDevdependenciesEslintPluginRxjsX) == ''">^1.0.6</PackageJsonDevdependenciesEslintPluginRxjsX>
    <PackageJsonDevdependenciesEslintPluginUnicorn Condition="$(PackageJsonDevdependenciesEslintPluginUnicorn) == ''">^64.0.0</PackageJsonDevdependenciesEslintPluginUnicorn>
    <PackageJsonDevdependenciesGlobals Condition="$(PackageJsonDevdependenciesGlobals) == ''">^17.11.0</PackageJsonDevdependenciesGlobals>
    <PackageJsonDevdependenciesJsdom Condition="$(PackageJsonDevdependenciesJsdom) == ''">^29.1.1</PackageJsonDevdependenciesJsdom>
    <PackageJsonDevdependenciesJsoncEslintParser Condition="$(PackageJsonDevdependenciesJsoncEslintParser) == ''">^3.3.0</PackageJsonDevdependenciesJsoncEslintParser>
    <PackageJsonDevdependenciesMergePartially Condition="$(PackageJsonDevdependenciesMergePartially) == ''">^2.0.2</PackageJsonDevdependenciesMergePartially>
    <PackageJsonDevdependenciesPostcss Condition="$(PackageJsonDevdependenciesPostcss) == ''">^8.5.23</PackageJsonDevdependenciesPostcss>
    <PackageJsonDevdependenciesRunScriptOs Condition="$(PackageJsonDevdependenciesRunScriptOs) == ''">^1.1.6</PackageJsonDevdependenciesRunScriptOs>
    <PackageJsonDevdependenciesTailwindcss Condition="$(PackageJsonDevdependenciesTailwindcss) == ''">^4.3.3</PackageJsonDevdependenciesTailwindcss>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">~6.0.3</PackageJsonDevdependenciesTypescript>
    <PackageJsonDevdependenciesTypescriptEslint Condition="$(PackageJsonDevdependenciesTypescriptEslint) == ''">^8.68.0</PackageJsonDevdependenciesTypescriptEslint>
    <PackageJsonDevdependenciesVitest Condition="$(PackageJsonDevdependenciesVitest) == ''">^4.1.11</PackageJsonDevdependenciesVitest>
  </PropertyGroup>
</Project>