CREATE TABLE [dbo].[ContactAlert]
(
	[Id] INT IDENTITY(1,1) CONSTRAINT PK_ContactAlert PRIMARY KEY,
	[EmailAddress] NVARCHAR(255) NOT NULL,
	[Name] NVARCHAR(255) NULL,
	[Message] NVARCHAR(MAX) NULL,
	[DateRequested] DATETIMEOFFSET NULL,
	[DateCreated] DATETIMEOFFSET CONSTRAINT DF_ContactAlert_DateCreated DEFAULT (SYSDATETIMEOFFSET()) NOT NULL
);
