name: Angular

on:
  push:
    branches:
    - main
    paths:
    - 'src/BHS.Web/ClientApp/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/BHS.Web/ClientApp/**'

defaults:
  run:
    working-directory: ./src/BHS.Web/ClientApp

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run lint

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build:app:prod

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run test:ci
    - run: npm run e2e:ci
