name: .NET

on:
  push:
    branches:
    - main
    paths:
    - 'BHS.sln'
    - 'src/**'
    - '!src/BHS.Web/ClientApp/**'
    - 'tests/**'
  pull_request:
    branches:
    - main
    paths:
    - 'BHS.sln'
    - 'src/**'
    - '!src/BHS.Web/ClientApp/**'
    - 'tests/**'

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ macOS-latest, ubuntu-latest, windows-latest ]

    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: dotnet restore
    - name: Run dotnet build
      run: dotnet build --no-restore --configuration Release
    - name: Run dotnet test
      run: dotnet test --no-build --configuration Release --verbosity normal
