name: Scheduled Smoke Tests

on:
  schedule:
  - cron: '49 11 * * 6' # 11:49 UTC on Saturdays
  
jobs:
  smoke-test-stage:
    uses: ./.github/workflows/smoke.yml
    with:
      environment: staging
    secrets: inherit

  smoke-test-prod:
    uses: ./.github/workflows/smoke.yml
    with:
      environment: production
    secrets: inherit
