name: Smoke Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The GitHub Actions environment of the subject under test.
        required: false
        type: choice
        options:
        - staging
        - production
        default: staging
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      CYPRESS_AUTH0_TEST_PASSWORD:
        required: true

env:
  CLIENTAPP_DIRECTORY: ./src/BHS.Web/ClientApp
  NODE_VERSION: '18'

jobs:
  smoke:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    
    - uses: actions/checkout@v3
  
    - name: Setup Node.js with caching
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
        cache-dependency-path: '${{ env.CLIENTAPP_DIRECTORY }}/package-lock.json'
  
    - name: cypress run
      uses: cypress-io/github-action@v5
      with:
        config-file: cypress/configFiles/cypress.config.smoke.ts
        working-directory: ${{ env.CLIENTAPP_DIRECTORY }}
        config: baseUrl=${{ vars.CYPRESS_BASE_URL }}
      env:
        CYPRESS_auth0Domain: ${{ vars.CYPRESS_AUTH0_DOMAIN }}
        CYPRESS_auth0ClientId: ${{ vars.CYPRESS_AUTH0_CLIENT_ID }}
        CYPRESS_auth0Audience: ${{ vars.CYPRESS_AUTH0_AUDIENCE }}
        CYPRESS_auth0TestUsername: ${{ vars.CYPRESS_AUTH0_TEST_USERNAME }}
        CYPRESS_auth0TestPassword: ${{ secrets.CYPRESS_AUTH0_TEST_PASSWORD }}

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: ${{ env.CLIENTAPP_DIRECTORY }}/cypress/screenshots

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: ${{ env.CLIENTAPP_DIRECTORY }}/cypress/videos
