name: Smoke Tests

on:
  workflow_dispatch: {}

env:
  CYPRESS_BASE_URL: https://staging.beltonhistoricalsociety.org/
  NODE_VERSION: '18'
  CLIENTAPP_DIRECTORY: ./src/BHS.Web/ClientApp

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
  
    - name: Setup Node.js with caching
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
        cache-dependency-path: '${{ env.CLIENTAPP_DIRECTORY }}/package-lock.json'
  
    - name: cypress run
      uses: cypress-io/github-action@v5
      with:
        config-file: cypress/configFiles/cypress.config.smoke.ts
        working-directory: ${{ env.CLIENTAPP_DIRECTORY }}
